# Generated by Django 4.2.3 on 2023-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='insizeimage',
            field=models.URLField(default='https://2626731.weebly.com/uploads/1/0/9/3/109388399/20-1_orig.jpg'),
            preserve_default=False,
        ),
    ]
