# Generated by Django 4.2.3 on 2023-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_insizeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.URLField(default='https://2626731.weebly.com/uploads/1/0/9/3/109388399/942654648_orig.jpg'),
            preserve_default=False,
        ),
    ]
