# Generated by Django 4.2.3 on 2023-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], max_length=15),
        ),
    ]
