# Generated by Django 4.2.3 on 2023-08-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Recieved", "Recieved"),
                    ("Delivered", "Delivered"),
                    ("On the way", "On the way"),
                ],
                max_length=15,
            ),
        ),
    ]
