# Generated by Django 4.2.3 on 2023-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_paypal_transaction_id_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Recieved', 'Recieved'), ('On the way', 'On the way')], max_length=15),
        ),
    ]
